backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Imagen", name: "image", widget: "image" }
